POST http://localhost:3000/api/category HTTP/1.1
content-type: application/json

{
    "category_name": "nombreC",
    "description": "descripcionC",
    "like_count": 10,
    "seasonal_product_available":0
}
###

GET http://localhost:3000/api/category HTTP/1.1

###
GET http://localhost:3000/api/category/3 HTTP/1.1

###

DELETE http://localhost:3000/api/category/2 HTTP/1.1


###
PUT http://localhost:3000/api/category/3 HTTP/1.1
content-type: application/json

{
    "id_category":3,
    "category_name": "nombreC2",
    "description": "descripcionC2"
}