POST http://localhost:3000/api/product HTTP/1.1
content-type: application/json

{
    "product_name": "pr1",
    "price": 3.29,
    "id_category": 1,
    "in_stock":1
}
###

GET http://localhost:3000/api/product HTTP/1.1

###
GET http://localhost:3000/api/product/2 HTTP/1.1

###

DELETE http://localhost:3000/api/product/2 HTTP/1.1


###
PUT http://localhost:3000/api/product/3 HTTP/1.1
content-type: application/json

{
    "id_product":3,
    "product_name": "nombreP2",
    "price": 1.11
}